scenario_dict = {
    "scenario_1.1": [20, 5, 0, 'FMNIST', 'nonuniform', 'None'],
    "scenario_1.2": [30, 5, 0, 'FMNIST', 'nonuniform', 'None'],
    "scenario_1.3": [40, 5, 0, 'FMNIST', 'nonuniform', 'None'],
    "scenario_2.1": [40, 0, 0, 'FMNIST', 'nonuniform', 'None'],
    "scenario_2.2": [40, 2, 0, 'FMNIST', 'nonuniform', 'None'],
    "scenario_2.3": [40, 5, 0, 'FMNIST', 'nonuniform', 'None'],
    "scenario_3.0": [40, 5, 0, 'FMNIST', 'nonuniform', 'None'],
    "scenario_3.1": [40, 5, 1, 'FMNIST', 'nonuniform', 'None'],
    "scenario_3.2": [40, 5, 2, 'FMNIST', 'nonuniform', 'None'],
    "scenario_3.3": [40, 5, 3, 'FMNIST', 'nonuniform', 'None'],
    "scenario_3.4": [40, 5, 4, 'FMNIST', 'nonuniform', 'None'],
    "scenario_3.5": [40, 5, 5, 'FMNIST', 'nonuniform', 'None'],
    "scenario_3.6": [40, 5, 6, 'FMNIST', 'nonuniform', 'None'],
    "scenario_3.7": [40, 5, 7, 'FMNIST', 'nonuniform', 'None'],
    "scenario_3.8": [40, 5, 8, 'FMNIST', 'nonuniform', 'None'],
    "scenario_3.9": [40, 5, 9, 'FMNIST', 'nonuniform', 'None'],
    "scenario_4.1": [40, 5, 0, 'FMNIST', 'nonuniform', 'None'],
    "scenario_4.2": [40, 5, 0, 'MNIST', 'nonuniform', 'None'],
    "scenario_5.1": [40, 5, 0, 'FMNIST', 'nonuniform', 'None'],
    "scenario_5.2": [40, 5, 0, 'FMNIST', 'uniform', 'None'],
    "scenario_6.1": [40, 5, 0, 'FMNIST', 'nonuniform', 'None'],
    "scenario_6.2": [40, 5, 0, 'FMNIST', 'nonuniform', 'random'],
    "scenario_6.3": [40, 5, 0, 'FMNIST', 'nonuniform', 'grouped'],
}